services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    restart: on-failure

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: on-failure

  video-processor:
    build:
      context: ./video-processor
    container_name: video-processor
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:29092
      PORT: 4001
    ports:
      - "4001:4001"
    volumes:
      - storage:/storage
    restart: on-failure

  video-streaming:
    build:
      context: ./video-streaming
    container_name: video-streaming
    depends_on:
      - backend
    environment:
      PORT: 3003
      STORAGE_HOST: http://localhost:8080
    ports:
      - "3003:3003"
    volumes:
      - storage:/storage
    restart: on-failure 

  postgres:
    image: postgres:15
    container_name: streaming-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: streaming
      POSTGRES_USER: streaming
      POSTGRES_PASSWORD: streaming
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure  

  backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      container_name: backend
      depends_on:
        - kafka
        - postgres
        - jaeger
      environment:
        KAFKA_BROKER: kafka:29092
        DATABASE_URL: postgres://streaming:streaming@postgres:5432/streaming
        JAEGER_ENDPOINT: "http://jaeger:14268/api/traces"
        PORT: 3001
        COOKIE_SECRET: "supersecret"
        DATABASE_HOST: postgres
        DATABASE_PORT: 5432
        DATABASE_USER: streaming
        DATABASE_PASSWORD: streaming
        DATABASE_NAME: streaming
        JWT_SECRET: HyywqAF76ltr+u91zWBWp4+KkEaI4gw0Pvw9pPDIP4w=
        API_BASE_URL: http://localhost:3001
        THUMBNAIL_BASE_URL: http://localhost:8080
        CORS_ORIGINS: "http://localhost:3000,http://frontend:3000"
        NODE_ENV: production
      ports:
        - "3001:3001"
      volumes:
        - storage:/storage
      restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    environment:
      NUXT_API_BASE_URL: http://backend:3001
      NUXT_PUBLIC_VIDEO_STREAM_HOST: http://localhost:3003
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    restart: on-failure

  jaeger:
    image: jaegertracing/all-in-one:1.41
    container_name: jaeger
    ports:
      - "16686:16686" 
      - "4318:4318" 
      - "14268:14268"    
      - "6831:6831/udp"  
    restart: on-failure      

  k6:
    build:
      context: ./k6
      dockerfile: Dockerfile
    depends_on:
      - backend
    volumes:
      - ./k6/scripts:/scripts
    environment:
      BACKEND_URL: "http://backend:3001"
      K6_VUS: 10
      K6_DURATION: "30s"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend
    restart: on-failure

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3002:3000"
    depends_on:
      - prometheus
    restart: on-failure

  nginx:
    image: nginx:alpine
    container_name: streaming-nginx
    depends_on:
      - video-processor
    ports:
      - "8080:80"
    volumes:
      - storage:/storage:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    restart: on-failure

volumes:
  postgres_data:
  storage: