name: Frontend CI/CD

defaults:
  run:
    working-directory: ./frontend

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build DEV image
        run: |
          docker build \
            -f Dockerfile.dev \
            -t frontend:dev .
      # Executado apenas testes que não dependem de banco de dados para demonstração
      - name: Run unit tests
        run: |
          docker run --rm frontend:dev npm run test:unit
      - name: Build PROD image
        run: |
          docker build \
            -f Dockerfile.prod \
            -t frontend:prod .
      # =========================================================
      # CD - Exemplo – Produção (executado apenas na branch main)
      # =========================================================

      # - name: Log in to Docker Hub
      #   if: github.ref == 'refs/heads/main'
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Push PROD image
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/frontend:latest
      #     docker tag frontend:prod $IMAGE_NAME
      #     docker push $IMAGE_NAME

      # - name: Terraform Init & Apply
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     cd terraform
      #     terraform init
      #     terraform apply -auto-approve
