name: Frontend CI/CD

defaults:
  run:
    working-directory: ./frontend

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [main]

jobs:
  build-test-and-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build DEV image
        run: |
          docker build \
            -f Dockerfile.dev \
            -t frontend:dev .
      - name: Run unit tests
        run: |
          docker run --rm frontend:dev npm run test:unit
      - name: Build PROD image
        run: |
          docker build \
            -f Dockerfile.prod \
            -t frontend:prod .